remote_theme: pmarsceill/just-the-docs
title: Servoy Guides
description: Root for all Servoy documentation
color_scheme: servoy
search_enabled: false
toc: true
logo: https://www.servoy.com/wp-content/themes/servoy/images/logo-servoy.png
ga_tracking: UA-299123-7